# Generated by Django 4.2.8 on 2024-03-28 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('bot_id', models.IntegerField(blank=True, null=True)),
                ('msg_id', models.IntegerField(blank=True, null=True)),
                ('crteated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Debtors',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('place_of_residence', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('passport_infos', models.CharField(max_length=10)),
                ('date_of_issue', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=150)),
                ('contract_number', models.AutoField(primary_key=True, serialize=False)),
                ('advance_payment', models.IntegerField()),
                ('total_debt', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('montly_payment', models.IntegerField()),
                ('months', models.IntegerField()),
                ('which_operator', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('contracts_count', models.IntegerField(blank=True, null=True)),
                ('msg_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
