# Generated by Django 4.2.8 on 2024-03-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='referral_link',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
