# Generated by Django 4.2.8 on 2024-03-28 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_operator_referral_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refferral_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_link', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='referral_link',
        ),
    ]
