# Generated by Django 4.2.8 on 2024-03-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_refferral_link_remove_operator_referral_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refferral_link',
            name='is_active',
        ),
    ]
