# Generated by Django 4.2.8 on 2024-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_refferral_link_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='last_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
