# Generated by Django 4.2.8 on 2024-03-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_creator_last_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='last_button',
            new_name='last_button_text',
        ),
    ]
