# Generated by Django 4.2.8 on 2024-03-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_last_button_creator_last_button_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debtors',
            new_name='Customer',
        ),
    ]
