# Generated by Django 4.2.8 on 2024-03-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer_operator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport_infos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
