# Generated by Django 4.2.8 on 2024-03-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_customer_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='docx_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
