# Generated by Django 4.2.8 on 2024-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customer_docx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='operator_id',
            field=models.IntegerField(default='example.docx'),
        ),
    ]
