# Generated by Django 4.2.8 on 2024-03-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_customer_operator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='docx_file',
            field=models.FileField(default='example.docx', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='operator_id',
            field=models.IntegerField(),
        ),
    ]
