# Generated by Django 4.2.8 on 2024-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_customer_docx_file_alter_customer_operator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='docx_file',
            field=models.FileField(upload_to='example.docx'),
        ),
    ]
