# Generated by Django 4.2.8 on 2024-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_customer_docx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='docx_file',
            field=models.FileField(default='example/example.docx', upload_to='example/'),
        ),
    ]
