# Generated by Django 4.2.8 on 2024-03-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_customer_docx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='docx_file',
            field=models.FileField(default='Example/example.docx', upload_to='Example/'),
        ),
    ]
