# Generated by Django 4.2.8 on 2024-03-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_operator_last_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='msg_id2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
