# Generated by Django 4.2.8 on 2024-03-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_operator_msg_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='msg_id3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
