# Generated by Django 4.2.8 on 2024-04-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_operator_msg_id4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='docx_file',
            field=models.FileField(upload_to=''),
        ),
    ]
