# Generated by Django 4.2.8 on 2024-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_customer_docx_file_customer_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='msg_id2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
