# Generated by Django 4.2.8 on 2024-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_creator_last_opr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='msg_id3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
