# Generated by Django 4.2.8 on 2024-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_creator_msg_id3'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
